### 넘파이 배열
- 리스트와의 비교
  - 리스트는 여러 종류의 자료형 및 값들을 저장할 수 있는 자료구조. 
  - 데이터를 변경하거나 추가, 제거도 가능

In [2]:
scores = [10, 20, 30, 40, 50, 60]
print(scores)

[10, 20, 30, 40, 50, 60]


    - 하지만 연산속도가 느림
- 보다 최적화가 잘 되어 있는 넘파이Numpy를 선호
- 넘파이: 대용량의 배열과 행렬 연산을 빠르게 수행하며, 고차원적인 수학 연산자와 함수를 포함하고 있는 파이썬 라이브러리
- 리스트에 비하여 처리속도가 매우 빠름

- 넘파이의 핵심적인 객체: 다차원 배열
  - Ex 정수들의 2차원 배열(테이블)을 넘파이를 이용해서 생성가능 & 배열의 각 요소는 인덱스index라고 불리는 정수들로 참조됨
- 넘파이에서 차원은 축axis이라고도 함

### ndarray 객체
- `ndarray` 는 C 언어에 기반한 배열 구조이므로 메모리를 적게 차지하고 속도가 빠름
- `ndarray` 를 사용하면 배열과 배열 간에 수학적인 연산을 적용 가능
- `ndarray` 는 고급 연산자와 풍부한 함수들을 제공

### 넘파이 패키지
- 넘파이 패키지를 불러오는 방법
- `import ~ as`에서 `as` 뒤에 나타나는 이름은 `as` 앞의 이름을 대체하는 별칭
- 보통 numpy의 별칭`alias`으로 `np`를 사용함
- 넘파이 배열을 만들려면 넘파이가 제공하는 `array( )` 함수를 이용해야함
- `array( )` 함수에 파이썬 리스트를 전달하면 넘파이 배열이 생성된다

In [3]:
import numpy as np

mid_scores = np.array([10, 20, 30])
fin_scores = np.array([60, 70, 80])

total_scores = mid_scores + fin_scores
print('시험 성적의 합계 :', total_scores)
print('시험 성적의 평균 :', total_scores/2)

시험 성적의 합계 : [ 70  90 110]
시험 성적의 평균 : [35. 45. 55.]


### 다차원배열
- 다차원배열의 속성
- `.shape`, `.ndim`, `.dtype`, `.itemsize`, `.size` 등을 활용하여 정보 추출 가능

In [4]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a.shape)
print(a.ndim)
print(a.dtype)
print(a.itemsize)
print(a.size)

(6,)
1
int32
4
6


### 넘파이 배열 연산
- 덧셈
- 곱셈

In [12]:
import numpy as np
salary = np.array([200, 250, 230])
print(salary)

salary += 100
print(salary)

salary = np.array([200, 250, 230])
salary *= 2
print(salary)

[200 250 230]
[300 350 330]
[400 500 460]


- 넘파이 배열의 특징: 동일한 타입의 데이터만 저장 가능
- *주의*: 여러 가지 타입을 섞어서 넘파이 배열에 전달하면 이를 모두 문자열로 변경함
- 넘파이 연산 속도가 빠른 이유: **동일한 데이터 타입으로 간주**하기 때문에 **항상 일정한 저장공간을 만들**어서 빠르게 접근이 가능함 → *임의 접근 random access*

In [18]:
scores = np.array([88, 72, 39, 94, 89, 78, 99])
print(scores[2])
print(scores[-1])
print(scores[1:4])

ages = np.array([18, 19, 20, 30, 28])
is_adult = ages > 19
print(is_adult)

39
99
[72 39 94]
[False False  True  True  True]


- 파이썬의 2차원 리스트
  - 리스트의 리스트
  - 수학에서의 행렬matrix와 비슷 / 단, 리스트는 행렬 연산을 지원 하지 않음

In [23]:
y = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
# python도 list 내의 list로 2차원 배열 선언을 제공은 함! 수학적 계산이 안될 뿐이지...
print(y)

y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# 또는
y = np.array(y)
print(y)

print(y[0][1])
print(y[0][2])
print(y[0][0])
print(y[1][2])

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
3
1
6


- 콤마를 사용하여 np_array[0, 2]로 써주어도 됨 ex) [row, col] 
- 콤마 앞에 값은 행을 나타내며, 콤마 뒤에 값은 열을 의미
- 배열 요소 변경 가능
- [주의] 파이썬 리스트와 달리, **넘파이 배열은 모든 항목이 동일한 자료형**을 가진다는 것을 명심. 
  - 예를 들어 *정수 배열에 부동 소수점 값을 삽입하려고 하면 소수점 이하값은 자동으로 사라짐*

In [26]:
print(y[1, 2])
print(y[0, -1])

y[2, 2] = 89
print(y[2, 2])

y[2, 2] = 0.4649
print(y[2, 2])
print(y)

6
3
89
0
[[1 2 3]
 [4 5 6]
 [7 8 0]]


넘파이 슬라이싱: 큰 행렬에서 작은 행렬을 끄집어내는 것으로 간주

In [29]:
np_array = np.array([[1,2,3,4], [5,6,7,8], [9, 10, 11, 12], [13, 14, 15, 16]])
print(np_array)

new_array = np_array[0:2, 2:4]
print(new_array)

new_array = np_array[::2, ::2]
print(new_array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[3 4]
 [7 8]]
[[ 1  3]
 [ 9 11]]


- `np_array` 배열내의 모든 원소들 중에서 5보다 큰 값만이 추출되어 `[6, 7, 8, 9]`와 같은 1차원 행렬이 출력되는 것을 볼 수 있다

In [38]:
new_array = np_array > 8
print(new_array)
print('\n')
new_array = np_array[np_array > 8]
print(new_array)

[[False False False False]
 [False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


[ 9 10 11 12 13 14 15 16]


#### arrange()
- `range()`와 비슷하지만 넘파이 배열을 생성
`- range()`와 `np.array()`를 쓰면 넘파이 배열이 만들어짐

In [5]:
print(np.arange(5))
print(np.arange(1, 6))
print(np.arange(1, 10, 2))
print(np.arange(0, 5, 2))

[0 1 2 3 4]
[1 2 3 4 5]
[1 3 5 7 9]
[0 2 4]


Sorted array is: [11, 12, 22, 25, 34, 64, 90]
